// flow-typed signature: 8d6b3849eac51209ac07ff7d76e5e8fb
// flow-typed version: <<STUB>>/@types/react_v^16.4.18/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
