// flow-typed signature: de354cfeefb39a732f6fb18c19a0ccb4
// flow-typed version: <<STUB>>/cross-env_v^3.1.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cross-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cross-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cross-env/dist/bin/cross-env' {
  declare module.exports: any;
}

declare module 'cross-env/dist/command' {
  declare module.exports: any;
}

declare module 'cross-env/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cross-env/dist/bin/cross-env.js' {
  declare module.exports: $Exports<'cross-env/dist/bin/cross-env'>;
}
declare module 'cross-env/dist/command.js' {
  declare module.exports: $Exports<'cross-env/dist/command'>;
}
declare module 'cross-env/dist/index.js' {
  declare module.exports: $Exports<'cross-env/dist/index'>;
}
