// flow-typed signature: 98f7eb81c6b4470b12e0cde7f90f2c40
// flow-typed version: <<STUB>>/karma-rollup-preprocessor_v^6.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-rollup-preprocessor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-rollup-preprocessor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-rollup-preprocessor/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/lib/index' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/fixtures/1' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/fixtures/2' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/fixtures/3' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/fixtures/4' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/fixtures/modules/a' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/fixtures/modules/b' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/t1' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/t2' {
  declare module.exports: any;
}

declare module 'karma-rollup-preprocessor/test/t3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-rollup-preprocessor/karma.conf.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/karma.conf'>;
}
declare module 'karma-rollup-preprocessor/lib/index.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/lib/index'>;
}
declare module 'karma-rollup-preprocessor/test/fixtures/1.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/fixtures/1'>;
}
declare module 'karma-rollup-preprocessor/test/fixtures/2.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/fixtures/2'>;
}
declare module 'karma-rollup-preprocessor/test/fixtures/3.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/fixtures/3'>;
}
declare module 'karma-rollup-preprocessor/test/fixtures/4.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/fixtures/4'>;
}
declare module 'karma-rollup-preprocessor/test/fixtures/modules/a.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/fixtures/modules/a'>;
}
declare module 'karma-rollup-preprocessor/test/fixtures/modules/b.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/fixtures/modules/b'>;
}
declare module 'karma-rollup-preprocessor/test/t1.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/t1'>;
}
declare module 'karma-rollup-preprocessor/test/t2.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/t2'>;
}
declare module 'karma-rollup-preprocessor/test/t3.js' {
  declare module.exports: $Exports<'karma-rollup-preprocessor/test/t3'>;
}
