// flow-typed signature: b0d21d36fb8b4bf204fc240ceca7337c
// flow-typed version: <<STUB>>/karma-cli_v^1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-cli/gruntfile' {
  declare module.exports: any;
}

declare module 'karma-cli/lib/log' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-cli/gruntfile.js' {
  declare module.exports: $Exports<'karma-cli/gruntfile'>;
}
declare module 'karma-cli/lib/log.js' {
  declare module.exports: $Exports<'karma-cli/lib/log'>;
}
