// flow-typed signature: 7024d65f83c5fb073ab998dfd4cbb7b8
// flow-typed version: <<STUB>>/karma-jasmine-html-reporter_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-jasmine-html-reporter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-jasmine-html-reporter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-jasmine-html-reporter/src/index' {
  declare module.exports: any;
}

declare module 'karma-jasmine-html-reporter/src/lib/adapter' {
  declare module.exports: any;
}

declare module 'karma-jasmine-html-reporter/src/lib/html.jasmine.reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-jasmine-html-reporter/src/index.js' {
  declare module.exports: $Exports<'karma-jasmine-html-reporter/src/index'>;
}
declare module 'karma-jasmine-html-reporter/src/lib/adapter.js' {
  declare module.exports: $Exports<'karma-jasmine-html-reporter/src/lib/adapter'>;
}
declare module 'karma-jasmine-html-reporter/src/lib/html.jasmine.reporter.js' {
  declare module.exports: $Exports<'karma-jasmine-html-reporter/src/lib/html.jasmine.reporter'>;
}
