// flow-typed signature: 420e727a2dde156837c831603a559501
// flow-typed version: <<STUB>>/karma-webpack_v^3.0.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-webpack/lib/index' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/karma-webpack' {
  declare module.exports: any;
}

declare module 'karma-webpack/lib/mocha-env-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-webpack/lib/index.js' {
  declare module.exports: $Exports<'karma-webpack/lib/index'>;
}
declare module 'karma-webpack/lib/karma-webpack.js' {
  declare module.exports: $Exports<'karma-webpack/lib/karma-webpack'>;
}
declare module 'karma-webpack/lib/mocha-env-loader.js' {
  declare module.exports: $Exports<'karma-webpack/lib/mocha-env-loader'>;
}
