// flow-typed signature: 6f93032595191fcbab5050652b8625e8
// flow-typed version: <<STUB>>/karma-chrome-launcher_v^2.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-chrome-launcher'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-chrome-launcher' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-chrome-launcher/examples/simple/index.spec' {
  declare module.exports: any;
}

declare module 'karma-chrome-launcher/examples/simple/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-chrome-launcher/gruntfile' {
  declare module.exports: any;
}

declare module 'karma-chrome-launcher/test/jsflags.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-chrome-launcher/examples/simple/index.spec.js' {
  declare module.exports: $Exports<'karma-chrome-launcher/examples/simple/index.spec'>;
}
declare module 'karma-chrome-launcher/examples/simple/karma.conf.js' {
  declare module.exports: $Exports<'karma-chrome-launcher/examples/simple/karma.conf'>;
}
declare module 'karma-chrome-launcher/gruntfile.js' {
  declare module.exports: $Exports<'karma-chrome-launcher/gruntfile'>;
}
declare module 'karma-chrome-launcher/index' {
  declare module.exports: $Exports<'karma-chrome-launcher'>;
}
declare module 'karma-chrome-launcher/index.js' {
  declare module.exports: $Exports<'karma-chrome-launcher'>;
}
declare module 'karma-chrome-launcher/test/jsflags.spec.js' {
  declare module.exports: $Exports<'karma-chrome-launcher/test/jsflags.spec'>;
}
