// flow-typed signature: ed9a465997f02c75b9aa682aec66cb86
// flow-typed version: <<STUB>>/rollup-plugin-license_v^0.8.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-license'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-license' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-license/dist/dependency' {
  declare module.exports: any;
}

declare module 'rollup-plugin-license/dist/eol' {
  declare module.exports: any;
}

declare module 'rollup-plugin-license/dist/generate-block-comment' {
  declare module.exports: any;
}

declare module 'rollup-plugin-license/dist/index-rollup-legacy' {
  declare module.exports: any;
}

declare module 'rollup-plugin-license/dist/index-rollup-stable' {
  declare module.exports: any;
}

declare module 'rollup-plugin-license/dist/index' {
  declare module.exports: any;
}

declare module 'rollup-plugin-license/dist/license-plugin' {
  declare module.exports: any;
}

declare module 'rollup-plugin-license/dist/person' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-license/dist/dependency.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/dependency'>;
}
declare module 'rollup-plugin-license/dist/eol.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/eol'>;
}
declare module 'rollup-plugin-license/dist/generate-block-comment.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/generate-block-comment'>;
}
declare module 'rollup-plugin-license/dist/index-rollup-legacy.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/index-rollup-legacy'>;
}
declare module 'rollup-plugin-license/dist/index-rollup-stable.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/index-rollup-stable'>;
}
declare module 'rollup-plugin-license/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/index'>;
}
declare module 'rollup-plugin-license/dist/license-plugin.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/license-plugin'>;
}
declare module 'rollup-plugin-license/dist/person.js' {
  declare module.exports: $Exports<'rollup-plugin-license/dist/person'>;
}
