// flow-typed signature: d42e0dd80ce1365cfe622e7ebac4b6de
// flow-typed version: <<STUB>>/@babel/plugin-proposal-class-properties_v^7.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-proposal-class-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-proposal-class-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-proposal-class-properties/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-proposal-class-properties/lib/index.js' {
  declare module.exports: $Exports<'@babel/plugin-proposal-class-properties/lib/index'>;
}
